### ISSUE TITLE
Incorrect intent in ccpp_MusicBox_suite_cap.F90

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#15]
When two schemes reference the same variable and the intent of the first scheme is "in" and the second scheme is "inout", the code for the generated MusicBox_suite_physics is mistakenly having the variable declared as "in".  This errors out during the make step.

To demonstrate this, clone MusicBox_cpf_0013 and checkout "cpf".  Then modify the intent for mass_quantities_util (.F90 and .meta) so that is intent "in" instead of "inout".  Intent "in" is what this routine should have the variable set as.  "inout" is my temporary workaround.

**Comment by gold2718** [comment]
Fixed in CPF_0.003
