### ISSUE TITLE
Names collision in generated code

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#16]
When two different routines use the same local name for variables which are matched to different standard names, the local name is entered twice into the ccpp_MusicBox_suite_cap.F90, which causes a compilation error.

To demonstrate this, clone cacraigucar/MusicBox and checkout hash e045a28732553141849c1fbdcd74377386070160.  Inside MusicBox_host/src/relhum/relhum_mod.F90 and .meta, remove "box" from in front of boxtemp, boxpress, boxh2ovmr, and boxrelhum in all locations.  "temp" will then collide with another module which is using a different local "temp" variable.

**Comment by gold2718** [comment]
Fixed in CPF_0.003
