### ISSUE TITLE
Dimensions are not properly checked

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#18]
I discovered that a scheme which is the second one called using the array o2_xsect had incorrect names for the dimension names in the .meta file.   There is no indication from the capgen routine that these dimension names are incorrect (not even valid names) and do not match the dimension names from the first scheme.

The files to demonstrate this bug are MICM_chemistry/src/tuv/oxygen_xsect/molec_ox_xsect.meta and MICM_chemistry/src/tuv/photo_rates/tuv_photolysis.meta.  This bug has existed in MICM_chemistry for at least the last month or so, so any recent version of MusicBox should demonstrate the problem.

**Comment by gold2718** [comment]
Loop variables should not be allowed in dimensions of init or final phase arguments.

**Comment by gold2718** [comment]
I believe this is fixed. The dimension checking has been completely re-implemented (as of CPF_0.2.015) so any new problems are probably new bugs and should have a new issue.
