### ISSUE TITLE
Add an attribute to not generate a call to a scheme's subroutine

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#22]
As the CPF interface expands to include 5 types of calls for each scheme, it will become more important to short circuit calling empty routines.  In the case of chemistry, this could eliminate hundreds of calls to empty routines on each time step.

I would propose that the requirement be that every metadata file lists the 5 types of scheme calls.  I would also propose a keyword at the ccpp-arg-table section of the metadata for a named scheme's subroutine which is something like:  "empty_scheme = true".   This would then trigger the CPF to pop this particular subroutine off of its stack of calls to generate.  

This has the added benefit that individual scheme .F90 files would only need to include the subroutine types which actually are needed and not need to write dummy routines for the others.

**Comment by gold2718** [comment]
What is the motivation to require metadata for schemes that do not need to exist? Why not just not have an empty scheme or metadata for it?

**Comment by cacraigucar** [comment]
According to discussions with Steve, the requirement of having empty placeholder routines went away awhile ago in the CPF. 

Because of this, this issue can be closed.
