### ISSUE TITLE
error checking / exception handling in suite cap

### ISSUE THREAD

**Issue by fvitt** [gold2718/ccpp-framework#23]
Error checking between invocation of scheme subroutines is missing in the suite cap code.  An exception was thrown by a scheme init (and run) without being caught.  The errflg was set to non-zero in the first scheme then reset to zero in the next scheme.   An exception needs to be thrown in ccpp_MusicBox_suite_cap code without moving on the the next scheme in the suite.

**Comment by gold2718** [comment]
Fixed in CPF_0.2.006
