### ISSUE TITLE
Framework needs to pass in available unit number(s) and filenames

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#24]
The CPF needs to pass in one or more available unit numbers for a scheme to use for its reading of namelists and static data.  It also needs to pass in the filename(s)

Perhaps the unit numbers become a specially identified variable in the metadata.  If more than one is requested, then they each need to be unique.

**Comment by gold2718** [comment]
I agree about filenames, however, we no longer need to worry about available unit numbers as the `newunit` keyword to `open` is widely supported.
As for filenames, all that is needed is a standard name for `namelist_filename`. Other data filenames will also have standard names which allow them to be identified.
