### ISSUE TITLE
variables in generated code should have commented standard name

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#28]
As the generated code uses variable names from underlying routines (which may have differing names), it would be useful to have standard names appended to the variable declarations as comments.  This will be useful for anyone examining the code and also for users who are copying sections to go back into non-ccpp code as they will need to translate these variables.

**Comment by gold2718** [comment]
Please suggest a format. The comment will go on the line immediately previous to the declaration.

**Comment by gold2718** [comment]
Fixed by https://github.com/NCAR/ccpp-framework/pull/273
