### ISSUE TITLE
xml_tools.py "call_command" fails in python 3.7

### ISSUE THREAD

**Issue by nusbaume** [gold2718/ccpp-framework#32]
While attempting to run the registry generator in CAMDEN with python 3.7, I ran into the following error:

```
File "/home/runner/work/repoForTestingCAM/repoForTestingCAM/src/data/generate_registry_data.py", line 1502, in gen_registry
    error_on_noxmllint=error_on_no_validate)
  File "/home/runner/work/repoForTestingCAM/repoForTestingCAM/ccpp_framework/scripts/parse_tools/xml_tools.py", line 200, in validate_xml_file
    result = call_command(cmd, logger)
  File "/home/runner/work/repoForTestingCAM/repoForTestingCAM/ccpp_framework/scripts/parse_tools/xml_tools.py", line 53, in call_command
    stderr=subprocess.STDOUT)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/subprocess.py", line 483, in run
    raise ValueError('stdout and stderr arguments may not be used '
ValueError: stdout and stderr arguments may not be used with capture_output.
```

After tracing it through, I believe it is due to this specific line of code in xml_tools.py (Line 51-53):

```
cproc = subprocess.run(commands, check=True,
                                       capture_output=True,
                                       stderr=subprocess.STDOUT)
```
which might no longer be allowed in Python version 3.7 or later, based off this text in the official 3.7 documentation:

> If capture_output is true, stdout and stderr will be captured. When used, the internal Popen object is automatically created with stdout=PIPE and stderr=PIPE. The stdout and stderr arguments may not be supplied at the same time as capture_output. If you wish to capture and combine both streams into one, use stdout=PIPE and stderr=STDOUT instead of capture_output.

The version of the code I am using to generate this error is tag `CPF_0.2.020`.

**Comment by gold2718** [comment]
I already had a special case for python 3.7+, I guess I never got to test it out.
@nusbaume, this should be fixed in CPF_0.2.021.
