### ISSUE TITLE
Generated code leads to error when run with NAG non-debug

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#33]
When running kessler using NAG in non-debug mode, get "Error: cam_ccpp_physics_finalize".  Inspecting the code it looks like the generated code for kessler_cam_finalize in ccpp_kessler_cam_cap needs to have errmsg and errflg changed to intent(inout) from intent(out).

I'm unable to test this theory as when I modify the code and do a case.build, it regenerates the cap.

**Comment by gold2718** [comment]
Should be fixed in CPF_0.2.022
