### ISSUE TITLE
ncol to timestep_init and finalize not working

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#4]
I get the following errors:

/home/cacraig/CPF_proto_new_cam_kessler/cam_driver/bin/ccpp/ccpp_cam_kessler_test_cap.F90:252:44:

       call kessler_timestep_finalize(col_end - col_start + 1, pver,            &
                                            1
Error: Symbol ‘col_end’ at (1) has no IMPLICIT type
/home/cacraig/CPF_proto_new_cam_kessler/cam_driver/bin/ccpp/ccpp_cam_kessler_test_cap.F90:252:56:

       call kessler_timestep_finalize(col_end - col_start + 1, pver,            &
                                                        1
Error: Symbol ‘col_start’ at (1) has no IMPLICIT type

This is the first time I'm trying to pass ncol to timestep_init and timestep_finalize.  The error occurs with both routines.

**Comment by gold2718** [comment]
`horizontal_loop_extent` is not a valid entry in init, final, timestep_init, or timestep_final methods. If a reasonable error message is not being shown, that would be a separate issue to open.
