### ISSUE TITLE
Bugs in autogenerated ccpp_cam_kessler_micm_cap.F90

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#5]
There is a "comma" in the private suite declarations when there are no specifiers for both integer and character variables.

/home/cacraig/CPF_proto_kessler_micm/cam_driver/bin/ccpp/ccpp_cam_kessler_micm_cap.F90:36:11:

    integer,                          :: nSpecies
           1
Error: Invalid character in name at (1)

These errors are in addition to the previously reported missing type.  NOTE - the type declaration will also need the use statement to bring it in.

/home/cacraig/CPF_proto_kessler_micm/cam_driver/bin/ccpp/ccpp_cam_kessler_micm_cap.F90:37:9:

    type(),             allocatable   :: cnst_info(:)
         1
Error: Invalid character in name at (1)

**Comment by cacraigucar** [comment]
There are also allocates for the integers.

The metadata for an example integer is:
!! [ njRxt ]
!!    standard_name = number_of_photolysis_reactions
!!    units = count
!!    dimensions = ()
!!    type = integer
!!    intent = out

**Comment by cacraigucar** [comment]
The arrays also need to have 1: added where they appear in the calling list

/home/cacraig/CPF_proto_kessler_micm/cam_driver/bin/ccpp/ccpp_cam_kessler_micm_cap.F90:261:27:

       call k_rateConst_run(k_rateConst(nkRxt), total_dens,                     &
                           1
Error: Rank mismatch in argument ‘k_rateconst’ at (1) (rank-1 and scalar)

**Comment by gold2718** [comment]
Fixed in CPF_0.0.8
